// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQWVq5lCNLYgLFhYrNI0w9nXESdh8WexQ',
    appId: '1:177267768234:android:e083027df0dd4f146d49d3',
    messagingSenderId: '177267768234',
    projectId: 'patience-healthcare-navigator',
    storageBucket: 'patience-healthcare-navigator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt7DKz9EYPSpR0xwbHmhzyWrxOYM0Jpe0',
    appId: '1:177267768234:ios:8c9465d84b6ca18b6d49d3',
    messagingSenderId: '177267768234',
    projectId: 'patience-healthcare-navigator',
    storageBucket: 'patience-healthcare-navigator.appspot.com',
    androidClientId: '177267768234-ujlv3b0nkfidilkgacr2pdvdqgntklsq.apps.googleusercontent.com',
    iosClientId: '177267768234-32lkev1r1bb3sm3slelajkkvalngdnu4.apps.googleusercontent.com',
    iosBundleId: 'com.patience.patiencehealthcarenav',
  );
}
